name: CD

on:
  release:
    types:
      - created

jobs:
  cd:
    name: npm Publish

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Get version
        uses: battila7/get-version-action@v2
        id: get_version

      - name: Set version
        run: npm --no-git-tag-version version ${{ steps.get_version.outputs.version-without-v }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run EsLint
        run: npx eslint --max-warnings 0 .

      - name: Run Prettier
        run: npx prettier --check .

      - name: Get publish tag
        uses: tobysmith568/npm-publish-latest-tag@v1
        id: latest_tag
        with:
          package-json: ./package.json

      - name: Publish
        run: npm publish --access public --provenance --tag ${{ steps.latest_tag.outputs.latest-tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
