name: npm Publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Get version from git tag
        uses: battila7/get-version-action@v2
        id: get_version

      - name: Set version in package.json
        run: npm --no-git-tag-version version ${{ steps.get_version.outputs.version-without-v }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Get publish tag
        uses: tobysmith568/npm-publish-latest-tag@v1
        id: latest_tag
        with:
          package-json: ./package.json

      - run: npm publish --access public --tag ${{ steps.latest_tag.outputs.latest-tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}